# Generated by Django 4.1.1 on 2022-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='source',
            field=models.URLField(default='https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/r5/json/NIST_SP-800-53_rev5_catalog.json', max_length=500),
        ),
    ]
